resolver: lts-5.14

# Local packages, usually specified by relative directory name
packages:
- '.'

# extra-deps: [OddWord-1.0.1.0,binary-bits-0.5,sequence-0.9.8]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
